/*********************************
 ******* @author Mr Exxon ********
 *********************************/
package Synopsis;
public class Exit extends javax.swing.JFrame {

    /**
     * Creates new form Exit
     */
    public Exit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txt_1 = new javax.swing.JLabel();
        txt_2 = new javax.swing.JLabel();
        txt_director1 = new javax.swing.JLabel();
        txt_director2 = new javax.swing.JLabel();
        txt_director3 = new javax.swing.JLabel();
        txt_tittle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/post2.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 490, 700);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1260, 10, 90, 40);

        txt_1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_1.setText("A rock climber tries to save the day when a mysterious white gas");
        jPanel1.add(txt_1);
        txt_1.setBounds(560, 230, 770, 40);

        txt_2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_2.setText("envelops an entire district in Seoul, South Korea.");
        jPanel1.add(txt_2);
        txt_2.setBounds(560, 270, 770, 40);

        txt_director1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_director1.setText("Director : Lee Sang-Geun");
        jPanel1.add(txt_director1);
        txt_director1.setBounds(560, 350, 300, 40);

        txt_director2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_director2.setText("Stars      : Jo Jung-suk, Im Yoon-ah, Ko Du-shim");
        jPanel1.add(txt_director2);
        txt_director2.setBounds(560, 430, 650, 40);

        txt_director3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_director3.setText("Writers  : Lee Sang-Geun");
        jPanel1.add(txt_director3);
        txt_director3.setBounds(560, 390, 300, 40);

        txt_tittle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txt_tittle.setText("EXIT");
        jPanel1.add(txt_tittle);
        txt_tittle.setBounds(560, 40, 560, 140);

        jLabel1.setBackground(new java.awt.Color(240, 240, 209));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/red_lines_background_texture_69795_1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_1;
    private javax.swing.JLabel txt_2;
    private javax.swing.JLabel txt_director1;
    private javax.swing.JLabel txt_director2;
    private javax.swing.JLabel txt_director3;
    private javax.swing.JLabel txt_tittle;
    // End of variables declaration//GEN-END:variables
}
