/** *******************************
 ******* @author Mr Exxon ********
 ******************************** */
package FOXID;

import javax.swing.JOptionPane;
import Logic.Login;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fadhal
 */
public class FoxMenu extends javax.swing.JFrame {

    String id, password;

    /**
     * Creates new form FoxMenu
     */
    public FoxMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        df_id = new javax.swing.JLabel();
        df_pass = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        txt_AccountId = new javax.swing.JLabel();
        txt_Pass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        df_id.setForeground(new java.awt.Color(204, 204, 204));
        df_id.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        df_id.setText("Admin");
        jPanel1.add(df_id);
        df_id.setBounds(980, 560, 70, 14);

        df_pass.setForeground(new java.awt.Color(204, 204, 204));
        df_pass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        df_pass.setText("Admin2020");
        jPanel1.add(df_pass);
        df_pass.setBounds(960, 650, 90, 14);

        txt_id.setFont(new java.awt.Font("Monospaced", 3, 48)); // NOI18N
        jPanel1.add(txt_id);
        txt_id.setBounds(710, 520, 350, 60);

        txt_password.setFont(new java.awt.Font("Monospaced", 3, 48)); // NOI18N
        jPanel1.add(txt_password);
        txt_password.setBounds(710, 610, 350, 60);

        btn_login.setBackground(new java.awt.Color(0, 0, 0));
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 0, 0));
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login);
        btn_login.setBounds(1090, 520, 180, 150);

        btn_exit.setBackground(new java.awt.Color(0, 0, 0));
        btn_exit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-power-off-button-64.png"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit);
        btn_exit.setBounds(1250, 690, 90, 70);

        txt_AccountId.setBackground(new java.awt.Color(2, 2, 2));
        txt_AccountId.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        txt_AccountId.setForeground(new java.awt.Color(255, 255, 255));
        txt_AccountId.setText("Account ID :");
        txt_AccountId.setOpaque(true);
        jPanel1.add(txt_AccountId);
        txt_AccountId.setBounds(290, 520, 360, 64);

        txt_Pass.setBackground(new java.awt.Color(2, 2, 2));
        txt_Pass.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        txt_Pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_Pass.setText("Password   :");
        txt_Pass.setOpaque(true);
        jPanel1.add(txt_Pass);
        txt_Pass.setBounds(290, 610, 360, 64);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/fox.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // logika untuk login ke dalam sistem
        id = txt_id.getText();
        password = txt_password.getText();
        
        Login login = new Login();
        Boolean check_id = login.checkId(id);
        if (!check_id) {
            JOptionPane.showMessageDialog(rootPane,
                    "Please input alphabet name only!",
                    "Message", HEIGHT);
            txt_id.setText("");
            txt_id.requestFocus();
            txt_password.setText("");
            txt_password.requestFocus();
        }
        
        if (id.equals("Admin") && password.equals("Admin2020")) {
            JOptionPane.showMessageDialog(null, "Login Success");
            this.setVisible(false);
            new FoxLoading().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect Username or Password!");
            txt_id.setText(null);
            txt_password.setText(null);
            txt_id.requestFocus();
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Exit This Application", "WARNING !!!", JOptionPane.OK_OPTION);
        if (answer == JOptionPane.OK_OPTION) {
            JOptionPane.showMessageDialog(rootPane,
                    "Thank You",
                    "FOX.ID v1.0", HEIGHT);
            dispose();
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoxMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoxMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoxMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoxMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoxMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel df_id;
    private javax.swing.JLabel df_pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_AccountId;
    private javax.swing.JLabel txt_Pass;
    private javax.swing.JTextField txt_id;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
