/** *******************************
 ******* @author Mr Exxon ********
 ******************************** */
package FOXID;

import Synopsis.Synopsis;
import javax.swing.JOptionPane;

public class Menu extends javax.swing.JFrame {

    double jumlah;
    int banyak, harga, pilih, answer;
    String discount;
    int a, b, c, d;
    Synopsis synopsis = new Synopsis();
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup_judul = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txt_FOXID = new javax.swing.JLabel();
        txt_GREETING = new javax.swing.JLabel();
        A_Invoice = new javax.swing.JLabel();
        A_StudioType = new javax.swing.JLabel();
        A_Movie = new javax.swing.JLabel();
        A_Price = new javax.swing.JLabel();
        A_TotalTicket = new javax.swing.JLabel();
        A_Time = new javax.swing.JLabel();
        A_TotalPrice = new javax.swing.JLabel();
        A_TotalPricePromo = new javax.swing.JLabel();
        A_TotalPriceUpdate = new javax.swing.JLabel();
        A_CouponCode = new javax.swing.JLabel();
        A_Discount = new javax.swing.JLabel();
        A_Pay = new javax.swing.JLabel();
        A_Balance = new javax.swing.JLabel();
        pic_parasite = new javax.swing.JLabel();
        pic_exit = new javax.swing.JLabel();
        pic_birthday = new javax.swing.JLabel();
        pic_theman = new javax.swing.JLabel();
        pic_another = new javax.swing.JLabel();
        pic_money = new javax.swing.JLabel();
        cb_studio = new javax.swing.JComboBox<>();
        cb_time = new javax.swing.JComboBox<>();
        txt_movie = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_banyak = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_normal = new javax.swing.JTextField();
        txt_coupon = new javax.swing.JTextField();
        txt_disc = new javax.swing.JTextField();
        txt_total1 = new javax.swing.JTextField();
        txt_pay = new javax.swing.JTextField();
        txt_balance = new javax.swing.JTextField();
        rb_parasite = new javax.swing.JRadioButton();
        rb_exit = new javax.swing.JRadioButton();
        rb_birthday = new javax.swing.JRadioButton();
        rb_theman = new javax.swing.JRadioButton();
        rb_another = new javax.swing.JRadioButton();
        rb_money = new javax.swing.JRadioButton();
        btn_syn_parasite = new javax.swing.JButton();
        btn_syn_exit = new javax.swing.JButton();
        btn_syn_birthday = new javax.swing.JButton();
        btn_syn_theman = new javax.swing.JButton();
        btn_syn_another = new javax.swing.JButton();
        btn_syn_money = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_invoice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        btn_input = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_cek = new javax.swing.JButton();
        btn_cek1 = new javax.swing.JButton();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        txt_FOXID.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        txt_FOXID.setForeground(new java.awt.Color(255, 255, 204));
        txt_FOXID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_FOXID.setText("FOX.ID");
        jPanel1.add(txt_FOXID);
        txt_FOXID.setBounds(40, 70, 740, 80);

        txt_GREETING.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        txt_GREETING.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_GREETING.setText("Welcome to");
        jPanel1.add(txt_GREETING);
        txt_GREETING.setBounds(40, 10, 750, 80);

        A_Invoice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        A_Invoice.setText("INVOICE");
        jPanel1.add(A_Invoice);
        A_Invoice.setBounds(850, 50, 140, 30);

        A_StudioType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_StudioType.setText("Studio Type");
        jPanel1.add(A_StudioType);
        A_StudioType.setBounds(550, 170, 100, 30);

        A_Movie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_Movie.setText("Movie");
        jPanel1.add(A_Movie);
        A_Movie.setBounds(550, 240, 80, 20);

        A_Price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_Price.setText("Price (Ticket)");
        jPanel1.add(A_Price);
        A_Price.setBounds(550, 310, 100, 30);

        A_TotalTicket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_TotalTicket.setText("Total Ticket");
        jPanel1.add(A_TotalTicket);
        A_TotalTicket.setBounds(550, 380, 100, 30);

        A_Time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_Time.setText("Time");
        jPanel1.add(A_Time);
        A_Time.setBounds(670, 380, 60, 30);

        A_TotalPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_TotalPrice.setText("Total Price");
        jPanel1.add(A_TotalPrice);
        A_TotalPrice.setBounds(550, 460, 100, 30);

        A_TotalPricePromo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_TotalPricePromo.setText("Total Price (Promo)");
        jPanel1.add(A_TotalPricePromo);
        A_TotalPricePromo.setBounds(550, 540, 140, 17);

        A_TotalPriceUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_TotalPriceUpdate.setText("Total Price (Update)");
        jPanel1.add(A_TotalPriceUpdate);
        A_TotalPriceUpdate.setBounds(850, 540, 160, 17);

        A_CouponCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_CouponCode.setText("Coupon Code");
        jPanel1.add(A_CouponCode);
        A_CouponCode.setBounds(550, 610, 100, 30);

        A_Discount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_Discount.setText("DISCOUNT");
        jPanel1.add(A_Discount);
        A_Discount.setBounds(550, 680, 80, 30);

        A_Pay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_Pay.setText("Pay");
        jPanel1.add(A_Pay);
        A_Pay.setBounds(850, 610, 100, 30);

        A_Balance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_Balance.setText("Balance");
        jPanel1.add(A_Balance);
        A_Balance.setBounds(850, 680, 100, 30);

        pic_parasite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pic1.jpg"))); // NOI18N
        jPanel1.add(pic_parasite);
        pic_parasite.setBounds(40, 170, 140, 190);

        pic_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pic3.jpg"))); // NOI18N
        jPanel1.add(pic_exit);
        pic_exit.setBounds(200, 170, 140, 190);

        pic_birthday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pic4.jpg"))); // NOI18N
        jPanel1.add(pic_birthday);
        pic_birthday.setBounds(360, 170, 140, 190);

        pic_theman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pic5.jpg"))); // NOI18N
        jPanel1.add(pic_theman);
        pic_theman.setBounds(40, 440, 140, 190);

        pic_another.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pic2.jpg"))); // NOI18N
        jPanel1.add(pic_another);
        pic_another.setBounds(200, 440, 140, 190);

        pic_money.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pic6.jpg"))); // NOI18N
        jPanel1.add(pic_money);
        pic_money.setBounds(360, 440, 140, 190);

        cb_studio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_studio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "‏‏‎ ‎", "Regular Studio", "Gold Class", "4DX", "Velvet Room" }));
        cb_studio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_studioActionPerformed(evt);
            }
        });
        jPanel1.add(cb_studio);
        cb_studio.setBounds(550, 200, 240, 30);

        cb_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "‏‏‎ ‎", "11:30", "13:45", "15:00", "17:15", "19:30", "21:45" }));
        cb_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_timeActionPerformed(evt);
            }
        });
        jPanel1.add(cb_time);
        cb_time.setBounds(670, 410, 110, 40);

        txt_movie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_movieActionPerformed(evt);
            }
        });
        jPanel1.add(txt_movie);
        txt_movie.setBounds(550, 270, 230, 30);
        jPanel1.add(txt_price);
        txt_price.setBounds(550, 340, 230, 30);

        txt_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_banyakActionPerformed(evt);
            }
        });
        txt_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_banyakKeyReleased(evt);
            }
        });
        jPanel1.add(txt_banyak);
        txt_banyak.setBounds(550, 410, 100, 40);
        jPanel1.add(txt_total);
        txt_total.setBounds(550, 570, 230, 30);
        jPanel1.add(txt_normal);
        txt_normal.setBounds(550, 490, 230, 30);
        jPanel1.add(txt_coupon);
        txt_coupon.setBounds(550, 640, 150, 30);

        txt_disc.setText("0");
        jPanel1.add(txt_disc);
        txt_disc.setBounds(550, 710, 150, 30);

        txt_total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_total1);
        txt_total1.setBounds(850, 570, 240, 30);

        txt_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_payActionPerformed(evt);
            }
        });
        txt_pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_payKeyReleased(evt);
            }
        });
        jPanel1.add(txt_pay);
        txt_pay.setBounds(850, 640, 240, 30);
        jPanel1.add(txt_balance);
        txt_balance.setBounds(850, 710, 240, 30);

        btngroup_judul.add(rb_parasite);
        rb_parasite.setText("PARASITE");
        rb_parasite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_parasiteActionPerformed(evt);
            }
        });
        jPanel1.add(rb_parasite);
        rb_parasite.setBounds(40, 370, 140, 23);

        btngroup_judul.add(rb_exit);
        rb_exit.setText("EXIT");
        rb_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_exitActionPerformed(evt);
            }
        });
        jPanel1.add(rb_exit);
        rb_exit.setBounds(200, 370, 140, 23);

        btngroup_judul.add(rb_birthday);
        rb_birthday.setText("BIRTHDAY");
        rb_birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_birthdayActionPerformed(evt);
            }
        });
        jPanel1.add(rb_birthday);
        rb_birthday.setBounds(360, 370, 140, 23);

        btngroup_judul.add(rb_theman);
        rb_theman.setText("THE MAN STANDING NEXT");
        rb_theman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_themanActionPerformed(evt);
            }
        });
        jPanel1.add(rb_theman);
        rb_theman.setBounds(40, 640, 160, 23);

        btngroup_judul.add(rb_another);
        rb_another.setText("ANOTHER CHILD");
        rb_another.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_anotherActionPerformed(evt);
            }
        });
        jPanel1.add(rb_another);
        rb_another.setBounds(200, 640, 140, 23);

        btngroup_judul.add(rb_money);
        rb_money.setText("MONEY");
        rb_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_moneyActionPerformed(evt);
            }
        });
        jPanel1.add(rb_money);
        rb_money.setBounds(360, 640, 140, 23);

        btn_syn_parasite.setText("Movie Synopsis");
        btn_syn_parasite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_syn_parasiteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_syn_parasite);
        btn_syn_parasite.setBounds(40, 400, 140, 23);

        btn_syn_exit.setText("Movie Synopsis");
        btn_syn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_syn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_syn_exit);
        btn_syn_exit.setBounds(200, 400, 140, 23);

        btn_syn_birthday.setText("Movie Synopsis");
        btn_syn_birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_syn_birthdayActionPerformed(evt);
            }
        });
        jPanel1.add(btn_syn_birthday);
        btn_syn_birthday.setBounds(360, 400, 140, 23);

        btn_syn_theman.setText("Movie Synopsis");
        btn_syn_theman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_syn_themanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_syn_theman);
        btn_syn_theman.setBounds(40, 670, 140, 23);

        btn_syn_another.setText("Movie Synopsis");
        btn_syn_another.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_syn_anotherActionPerformed(evt);
            }
        });
        jPanel1.add(btn_syn_another);
        btn_syn_another.setBounds(200, 670, 140, 23);

        btn_syn_money.setText("Movie Synopsis");
        btn_syn_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_syn_moneyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_syn_money);
        btn_syn_money.setBounds(360, 670, 140, 23);

        btn_print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_print.setText("INVOICE");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        jPanel1.add(btn_print);
        btn_print.setBounds(1200, 560, 150, 90);

        btn_invoice.setText("PRINT");
        btn_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invoiceActionPerformed(evt);
            }
        });
        jPanel1.add(btn_invoice);
        btn_invoice.setBounds(1270, 480, 73, 23);

        txt_area.setColumns(20);
        txt_area.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(850, 90, 500, 420);

        btn_input.setBackground(new java.awt.Color(0, 0, 0));
        btn_input.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_input.setForeground(new java.awt.Color(255, 255, 255));
        btn_input.setText("ADD NEW ORDER");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        jPanel1.add(btn_input);
        btn_input.setBounds(1200, 660, 150, 100);

        btn_keluar.setBackground(new java.awt.Color(0, 0, 0));
        btn_keluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Log Out");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar);
        btn_keluar.setBounds(1257, 10, 80, 40);

        btn_cek.setBackground(new java.awt.Color(255, 51, 51));
        btn_cek.setForeground(new java.awt.Color(255, 255, 255));
        btn_cek.setText("check");
        btn_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cek);
        btn_cek.setBounds(710, 640, 70, 30);

        btn_cek1.setBackground(new java.awt.Color(255, 51, 51));
        btn_cek1.setForeground(new java.awt.Color(255, 255, 255));
        btn_cek1.setText("update");
        btn_cek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cek1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cek1);
        btn_cek1.setBounds(710, 710, 70, 30);

        BACKGROUND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/red.jpg"))); // NOI18N
        jPanel1.add(BACKGROUND);
        BACKGROUND.setBounds(0, 0, 1366, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_syn_birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_syn_birthdayActionPerformed
        /*
        Menampilkan Synopsis Film
         */
        synopsis.Birthday();
    }//GEN-LAST:event_btn_syn_birthdayActionPerformed

    private void btn_syn_parasiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_syn_parasiteActionPerformed
        /*
        Menampilkan Synopsis Film
         */
        synopsis.Parasite();
    }//GEN-LAST:event_btn_syn_parasiteActionPerformed

    private void btn_syn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_syn_exitActionPerformed
        /*
        Menampilkan Synopsis Film
         */
        synopsis.Exit();
    }//GEN-LAST:event_btn_syn_exitActionPerformed

    private void btn_syn_themanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_syn_themanActionPerformed
        /*
        Menampilkan Synopsis Film
         */
        synopsis.TheMan();
    }//GEN-LAST:event_btn_syn_themanActionPerformed

    private void btn_syn_anotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_syn_anotherActionPerformed
        /*
        Menampilkan Synopsis Film
         */
        synopsis.Another();
    }//GEN-LAST:event_btn_syn_anotherActionPerformed

    private void btn_syn_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_syn_moneyActionPerformed
        /*
        Menampilkan Synopsis Film
         */
        synopsis.Money();
    }//GEN-LAST:event_btn_syn_moneyActionPerformed

    private void cb_studioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_studioActionPerformed
        /*
        Membuat pricelist sesuai dengan tipe ruangan
         */
        if (cb_studio.getSelectedItem().equals("Regular Studio")) {
            txt_price.setText(String.valueOf(55000));
        } else if (cb_studio.getSelectedItem().equals("Gold Class")) {
            txt_price.setText(String.valueOf(85000));
        } else if (cb_studio.getSelectedItem().equals("4DX")) {
            txt_price.setText(String.valueOf(175000));
        } else if (cb_studio.getSelectedItem().equals("Velvet Room")) {
            txt_price.setText(String.valueOf(215000));
        }
    }//GEN-LAST:event_cb_studioActionPerformed

    private void txt_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_banyakActionPerformed

    }//GEN-LAST:event_txt_banyakActionPerformed

    private void txt_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_payActionPerformed
        
    }//GEN-LAST:event_txt_payActionPerformed

    private void rb_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_exitActionPerformed
        /*
        Menampilkan judul film sesuai dengan pilihan
         */
        if (rb_exit.isSelected()) {
            txt_movie.setText(String.valueOf("EXIT"));
        }
    }//GEN-LAST:event_rb_exitActionPerformed

    private void rb_birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_birthdayActionPerformed
        /*
        Menampilkan judul film sesuai dengan pilihan
         */
        if (rb_birthday.isSelected()) {
            txt_movie.setText(String.valueOf("BIRTHDAY"));
        }
    }//GEN-LAST:event_rb_birthdayActionPerformed

    private void rb_themanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_themanActionPerformed
        /*
        Menampilkan judul film sesuai dengan pilihan
         */
        if (rb_theman.isSelected()) {
            txt_movie.setText(String.valueOf("THE MAN STANDING NEXT"));
        }
    }//GEN-LAST:event_rb_themanActionPerformed

    private void rb_anotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_anotherActionPerformed
        /*
        Menampilkan judul film sesuai dengan pilihan
         */
        if (rb_another.isSelected()) {
            txt_movie.setText(String.valueOf("ANOTHER CHILD"));
        }
    }//GEN-LAST:event_rb_anotherActionPerformed

    private void rb_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_moneyActionPerformed
        /*
        Menampilkan judul film sesuai dengan pilihan
         */
        if (rb_money.isSelected()) {
            txt_movie.setText(String.valueOf("MONEY"));
        }
    }//GEN-LAST:event_rb_moneyActionPerformed

    private void rb_parasiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_parasiteActionPerformed
        /*
        Menampilkan judul film sesuai dengan pilihan
         */
        if (rb_parasite.isSelected()) {
            txt_movie.setText(String.valueOf("PARASITE"));
        }
    }//GEN-LAST:event_rb_parasiteActionPerformed

    private void txt_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_banyakKeyReleased
        /*
        Logika untuk menampilkan harga normal serta harga promo:
        Harga Normal = Harga Tiket * Banyak Tiket
         */
        a = Integer.valueOf(txt_price.getText());
        b = Integer.valueOf(txt_banyak.getText());
        c = (a * b);

        txt_normal.setText("" + c);

        if (c >= 440000) {
            c = (int) (c - (c * 0.15));
            txt_total.setText("" + c);
        } else if (jumlah >= 250000) {
            c = (int) (c - (c * 0.1));
            txt_total.setText("" + c);
        } else if (jumlah >= 170000) {
            c = (int) (c - (c * 0.07));
            txt_total.setText("" + c);
        } else {
            txt_total.setText("" + c);
        }


    }//GEN-LAST:event_txt_banyakKeyReleased

    private void txt_payKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_payKeyReleased
        /*
        Logika untuk menampilkan uang kembalian
        uang kembalian = (uang bayar - total pembelian) + discount
         */
        a = Integer.valueOf(txt_pay.getText());
        b = Integer.valueOf(txt_total.getText());
        d = Integer.valueOf(txt_disc.getText());
        c = d + a - b;
        txt_balance.setText("" + c);
    }//GEN-LAST:event_txt_payKeyReleased

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        /*
        Membuat halaman untuk menampilkan hasil pembelian
         */
        txt_area.setText(
                "《《《《《《《《《《》》》》》》》》》》" + "\n"
                + "         THE FOX THEATER‏‎" + "\n"
                + "             FOX.ID" + "\n"
                + "《《《《《《《《《《》》》》》》》》》》" + "\n"
                + "‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎‏‏‏‏‏‏‏‏‏‏‎ ‎‏‎ ‎‏‎ ‎‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎" + "\n"
                + "MOVIE         : " + txt_movie.getText() + "\n"
                + "TIME          : " + cb_time.getSelectedItem() + "\n"
                + "STUDIO TYPE   : " + cb_studio.getSelectedItem() + "\n"
                + "BUY‏‏‎           : " + txt_banyak.getText() + "\n"
                + "PRICE (one)   : Rp. " + txt_price.getText() + "\n"
                + "PRICE (normal)‏‎: Rp. " + txt_normal.getText() + "\n"
                + "PRICE ‎‏‏‎(Promo)‎ : Rp. " + txt_total.getText() + "\n"
                + "PRICE ‎(Disc)  : Rp. " + txt_total1.getText() + "\n"
                + "Pay‏‏‎           : Rp. " + txt_pay.getText() + "\n"
                + "Balance‏‏       : Rp. " + txt_balance.getText() + "\n"
        );
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        /*
        Fungsi untuk menghapus semua inputan dan pilihan
         */
        pilih = JOptionPane.showConfirmDialog(null, "Add New Order", "WARNING", JOptionPane.OK_OPTION);
        if (pilih == JOptionPane.OK_OPTION) {
            btngroup_judul.clearSelection();
            cb_studio.setSelectedItem("‏‏‎ ‎");
            cb_time.setSelectedItem("‏‏‎ ‎");
            txt_area.setText(null);
            txt_balance.setText(null);
            txt_banyak.setText(null);
            txt_coupon.setText(null);
            txt_movie.setText(null);
            txt_pay.setText(null);
            txt_price.setText(null);
            txt_total.setText("" + 0);
            txt_normal.setText("" + 0);
            txt_total1.setText("" + 0);
            txt_disc.setText("" + 0);
        }
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekActionPerformed
        /*
        Membuat Kode Discount untuk pengguna
        NONTON2020 = 30.000
        NONTONDIFOX = 25.000
        CUMADIFOXID = 40.000
         */
        discount = txt_coupon.getText();

        if (discount.equals("ONLYONFOXID")) {
            txt_disc.setText(String.valueOf("" + 30000));
        } else if (discount.equals("WATCHINGONFOXID")) {
            txt_disc.setText(String.valueOf("" + 25000));
        } else if (discount.equals("HAPPYFOXID")) {
            txt_disc.setText(String.valueOf("" + 40000));
        }
    }//GEN-LAST:event_btn_cekActionPerformed

    private void btn_cek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cek1ActionPerformed
        /*
        Logika untuk memotong harga tiket dengan ketentuan :
        pembelian > 170.000 mendapat diskon 7%
        pembelian > 250.000 mendapat diskon 10%
        pembelian > 440.000 mendapat diskon 15%
        Menampilkan Harga Tiket Final
         */
        int d = 0;
        a = Integer.valueOf(txt_total.getText());
        b = Integer.valueOf(txt_disc.getText());
        c = a - b;
        txt_total1.setText("" + c);

    }//GEN-LAST:event_btn_cek1ActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        /*
        Tombol untuk keluar dari halaman utama
        dan kembali lagi ke halaman Log In
         */
        answer = JOptionPane.showConfirmDialog(null, "LOG OUT", "WARNING !!!", JOptionPane.OK_OPTION);
        if (answer == JOptionPane.OK_OPTION) {
            JOptionPane.showMessageDialog(rootPane,
                    "Log Out Successful",
                    "FOX.ID v1.0", HEIGHT);
            this.dispose();
            FoxMenu utama = new FoxMenu();
            utama.setVisible(true);
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void txt_movieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_movieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_movieActionPerformed

    private void btn_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_invoiceActionPerformed
        /*
        Menampilkan nota pembelian
        fungsinya sama seperti printer
         */
        Struck struck = new Struck(txt_area.getText());
        struck.setVisible(true);
    }//GEN-LAST:event_btn_invoiceActionPerformed

    private void cb_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_timeActionPerformed

    private void txt_total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A_Balance;
    private javax.swing.JLabel A_CouponCode;
    private javax.swing.JLabel A_Discount;
    private javax.swing.JLabel A_Invoice;
    private javax.swing.JLabel A_Movie;
    private javax.swing.JLabel A_Pay;
    private javax.swing.JLabel A_Price;
    private javax.swing.JLabel A_StudioType;
    private javax.swing.JLabel A_Time;
    private javax.swing.JLabel A_TotalPrice;
    private javax.swing.JLabel A_TotalPricePromo;
    private javax.swing.JLabel A_TotalPriceUpdate;
    private javax.swing.JLabel A_TotalTicket;
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JButton btn_cek;
    private javax.swing.JButton btn_cek1;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_invoice;
    private javax.swing.JButton btn_keluar;
    public javax.swing.JButton btn_print;
    private javax.swing.JButton btn_syn_another;
    private javax.swing.JButton btn_syn_birthday;
    private javax.swing.JButton btn_syn_exit;
    private javax.swing.JButton btn_syn_money;
    private javax.swing.JButton btn_syn_parasite;
    private javax.swing.JButton btn_syn_theman;
    private javax.swing.ButtonGroup btngroup_judul;
    public javax.swing.JComboBox<String> cb_studio;
    public javax.swing.JComboBox<String> cb_time;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pic_another;
    private javax.swing.JLabel pic_birthday;
    private javax.swing.JLabel pic_exit;
    private javax.swing.JLabel pic_money;
    private javax.swing.JLabel pic_parasite;
    private javax.swing.JLabel pic_theman;
    public javax.swing.JRadioButton rb_another;
    public javax.swing.JRadioButton rb_birthday;
    public javax.swing.JRadioButton rb_exit;
    public javax.swing.JRadioButton rb_money;
    public javax.swing.JRadioButton rb_parasite;
    public javax.swing.JRadioButton rb_theman;
    private javax.swing.JLabel txt_FOXID;
    private javax.swing.JLabel txt_GREETING;
    private javax.swing.JTextArea txt_area;
    public javax.swing.JTextField txt_balance;
    public javax.swing.JTextField txt_banyak;
    private javax.swing.JTextField txt_coupon;
    private javax.swing.JTextField txt_disc;
    public javax.swing.JTextField txt_movie;
    public javax.swing.JTextField txt_normal;
    public javax.swing.JTextField txt_pay;
    public javax.swing.JTextField txt_price;
    public javax.swing.JTextField txt_total;
    public javax.swing.JTextField txt_total1;
    // End of variables declaration//GEN-END:variables
}
